# Generated by Django 5.2.7 on 2025-12-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_rename_saida_pedido_pedido_data_saida'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValorDiferente',
            new_name='TabelaPrecoCliente',
        ),
    ]
