# Generated by Django 5.2.7 on 2025-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('inscricao_estadual', models.CharField(max_length=50)),
            ],
        ),
    ]
