# Generated by Django 5.2.7 on 2025-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('saida_pedido', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagador_frete', models.CharField(blank=True, max_length=10, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('forma_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivo_adicional', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
