# Generated by Django 5.2.7 on 2025-12-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='saida_pedido',
            new_name='data_saida',
        ),
    ]
