# Generated by Django 6.0 on 2026-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_contato_created_at_contato_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('nome_razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('indicador_ie', models.IntegerField(choices=[(1, 'Contribuinte ICMS'), (2, 'Contribuinte Isento'), (3, 'Não Contribuinte')], default=9)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(max_length=15)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('codigo_municipio', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
