# Generated by Django 6.0 on 2026-01-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_cliente_bairro_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome_fantasia',
        ),
    ]
