# Generated by Django 6.0 on 2026-01-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_remove_cliente_nome_fantasia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_pessoa',
        ),
    ]
