# Generated by Django 6.0 on 2026-01-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_cliente_tipo_pessoa'),
        ('logistica', '0018_produto_cest_produto_cfop_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('natureza_operacao', models.CharField(default='Venda de Mercadoria', max_length=100)),
                ('meio_pagamento', models.CharField(choices=[('01', 'Dinheiro'), ('02', 'Cheque'), ('03', 'Cartão de Crédito'), ('04', 'Cartão de Débito'), ('15', 'Boleto Bancário'), ('17', 'PIX')], default='01', max_length=2)),
                ('modalidade_frete', models.IntegerField(choices=[(0, 'Por conta do emitente'), (1, 'Por conta do destinatário'), (2, 'Por conta de terceiros'), (9, 'Sem frete')], default=9)),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('peso_liquido', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('quantidade_volumes', models.IntegerField(default=1)),
                ('nfe_status', models.CharField(choices=[('pendente', 'Pendente de Envio'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('nfe_chave', models.CharField(blank=True, max_length=44, null=True)),
                ('nfe_numero', models.IntegerField(blank=True, null=True)),
                ('nfe_serie', models.IntegerField(blank=True, null=True)),
                ('nfe_protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('nfe_motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cfop', models.CharField(max_length=4)),
                ('icms_cst', models.CharField(default='101', max_length=3)),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icms_base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.pedido')),
            ],
        ),
    ]
