# Generated by Django 6.0 on 2026-01-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_pedido_contato_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='icms_aliquota',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='icms_base_calculo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
