# Generated by Django 6.0 on 2026-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_itempedido_icms_aliquota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
