# Generated by Django 6.0 on 2026-05-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_alter_pedido_peso_bruto_alter_pedido_peso_liquido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preco_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço do Frete'),
        ),
    ]
