# Generated by Django 6.0 on 2025-12-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_base', models.DecimalField(decimal_places=2, help_text='Preço de venda padrão', max_digits=10)),
                ('ncm', models.CharField(help_text='8 dígitos - Nomenclatura Comum do Mercosul', max_length=8)),
                ('unidade_medida', models.CharField(default='UN', help_text='Ex: UN, KG, PC, L', max_length=6)),
                ('origem', models.IntegerField(choices=[(0, 'Nacional'), (1, 'Estrangeira - Importação direta'), (2, 'Estrangeira - Adquirida no mercado interno')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
