# Generated by Django 6.0 on 2025-12-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_produto_created_at_produto_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='is_active',
            new_name='is_ativo',
        ),
    ]
