# Generated by Django 6.0 on 2025-12-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_rename_updated_at_produto_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='is_ativo',
            new_name='eh_ativo',
        ),
    ]
