# Generated by Django 6.0 on 2025-12-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_rename_is_ativo_produto_eh_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='eh_ativo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
    ]
