# Generated by Django 6.0 on 2025-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_rename_criado_em_produto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.IntegerField(choices=[(0, 'UN'), (1, 'KG'), (2, 'PC'), (3, 'L')], default=0),
        ),
    ]
