# Generated by Django 6.0 on 2025-12-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_alter_produto_unidade_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='is_active',
        ),
    ]
