# Generated by Django 6.0 on 2025-12-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_remove_produto_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportadora',
            old_name='nome_razao_social',
            new_name='razao_social',
        ),
    ]
