# Generated by Django 6.0 on 2025-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_rename_nome_razao_social_transportadora_razao_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportadora',
            old_name='razao_social',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
