# Generated by Django 6.0 on 2025-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_rename_razao_social_transportadora_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
