# Generated by Django 6.0 on 2025-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_transportadora_telefone_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='numero',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
