# Generated by Django 6.0 on 2025-12-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_transportadora_bairro_transportadora_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
