# Generated by Django 6.0 on 2025-12-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_transportadora_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
