# Generated by Django 6.0 on 2025-12-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_transportadora_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
