# Generated by Django 6.0 on 2025-12-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_alter_transportadora_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
