# Generated by Django 6.0 on 2025-12-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_transportadora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
