# Generated by Django 6.0 on 2026-01-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_alter_transportadora_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportadora',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='uf',
        ),
    ]
