# Generated by Django 6.0 on 2026-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_remove_transportadora_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.CharField(default='5102', max_length=4),
        ),
    ]
