# Generated by Django 6.0 on 2026-05-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_produto_cest_produto_cfop_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso_unitario',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Peso Unitário (kg)'),
        ),
    ]
